# Generated by Django 3.0.14 on 2022-06-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_detail', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial_app.UserInfo')),
            ],
        ),
    ]
